--- Makefile.original	2016-06-20 18:17:16.661787072 +0300
+++ Makefile	2016-06-20 18:18:39.577783863 +0300
@@ -686,17 +686,18 @@
 	  done; \
 	  test $$st -eq 0 || exit 1; \
 	fi
+	# MFG: Hack for identifying and aggregating test results in log.
 	@$(am__sh_e_setup); $(am__tty_colors); $(am__set_TESTS_bases); \
 	ws='[ 	]'; \
-	results=`for b in $$bases; do echo $$b.trs; done`; \
+	results=`for b in $$bases; do echo $$b.log; done`; \
 	test -n "$$results" || results=/dev/null; \
-	all=`  grep "^$$ws*:test-result:"           $$results | wc -l`; \
-	pass=` grep "^$$ws*:test-result:$$ws*PASS"  $$results | wc -l`; \
-	fail=` grep "^$$ws*:test-result:$$ws*FAIL"  $$results | wc -l`; \
-	skip=` grep "^$$ws*:test-result:$$ws*SKIP"  $$results | wc -l`; \
-	xfail=`grep "^$$ws*:test-result:$$ws*XFAIL" $$results | wc -l`; \
-	xpass=`grep "^$$ws*:test-result:$$ws*XPASS" $$results | wc -l`; \
-	error=`grep "^$$ws*:test-result:$$ws*ERROR" $$results | wc -l`; \
+	all=` grep ":.\+:.:.\+:.\+:.\+: "           $$results | wc -l`; \
+	pass=` grep "^.\+\.c:.\+:.:.\+:.\+:.\+: Passed"  $$results | wc -l`; \
+	fail=` grep "^.\+\.c:.\+:.:.\+:.\+:.\+: Assertion .\+ failed:"  $$results | wc -l`; \
+	skip=` grep "^.\+\.c:.\+:.:.\+:.\+:.\+: Skipped"  $$results | wc -l`; \
+	xfail=`grep "^.\+\.c:.\+:.:.\+:.\+:.\+: XFailed" $$results | wc -l`; \
+	xpass=`grep "^.\+\.c:.\+:.:.\+:.\+:.\+: XPassed" $$results | wc -l`; \
+	error=`grep ":.\+:.:.\+:.\+:.\+: (after this point) Received" $$results | wc -l`; \
 	if test `expr $$fail + $$xpass + $$error` -eq 0; then \
 	  success=true; \
 	else \
