.TH SGSH-PS 1 "15 July 2013"
.\"
.\" (C) Copyright 2013 Diomidis Spinellis.  All rights reserved.
.\"
.\"  Licensed under the Apache License, Version 2.0 (the "License");
.\"  you may not use this file except in compliance with the License.
.\"  You may obtain a copy of the License at
.\"
.\"      http://www.apache.org/licenses/LICENSE-2.0
.\"
.\"  Unless required by applicable law or agreed to in writing, software
.\"  distributed under the License is distributed on an "AS IS" BASIS,
.\"  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
.\"  See the License for the specific language governing permissions and
.\"  limitations under the License.
.\"
.SH NAME
sgsh-ps \- report process status in JSON format
.SH SYNOPSIS
\fBsgsh-ps\fP \fIprocess-id\fP
.SH DESCRIPTION
\fIsgsh-ps\fP will report the status of each descendant of
the process specified by \fIprocess-id\fP in JSON format.
The results are printed on the standard output as an array
containing an entry for each process.
Each entry contains at least two keys:
the command name in an entry named \fBcommand\fP, and
an array of key-value entries in an entry named \fBkv\fP.
Each entry of the array contains two values,
\fBk\fP, which is the key, and \fBv\fP, which is the value.
The key is a metric (e.g. user time) and the value is a human-readable
rendering of the corresponding measurement (e.g. 452KiB).
The precise number, wording, and format of the supported keys and values depends on the
underlying operating system.
.PP
The command is used internally by \fIsgsh\fP for the debugging user interface.

.SH "SEE ALSO"
\fIsgsh\fP(1)

.SH AUTHOR
Diomidis Spinellis \(em <http://www.spinellis.gr>
