.TH SGSH-HTTPVAL 1 "26 May 2013"
.\"
.\" (C) Copyright 2013 Diomidis Spinellis.  All rights reserved.
.\"
.\"  Licensed under the Apache License, Version 2.0 (the "License");
.\"  you may not use this file except in compliance with the License.
.\"  You may obtain a copy of the License at
.\"
.\"      http://www.apache.org/licenses/LICENSE-2.0
.\"
.\"  Unless required by applicable law or agreed to in writing, software
.\"  distributed under the License is distributed on an "AS IS" BASIS,
.\"  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
.\"  See the License for the specific language governing permissions and
.\"  limitations under the License.
.\"
.SH NAME
sgsh-httpval \- data store HTTP server
.SH SYNOPSIS
\fBsgsh-httpval\fP
[\fB\-a\fP]
[\fB\-m\fP \fIMIME-type\fP]
[\fB\-p\fP \fIport\fP]
.SH DESCRIPTION
\fIsgsh-httpval\fP allows other programs to access \fIsgsh\fP
data stores through the HTTP protocol.
This simplifies the interfacing between web-based front-ends and
\fIsgsh\fP programs.
When \fIsgsh-httpval\fP receives a REST request with the name of a data store
whose endpoint is located in the directory where \fIsgsh-httpval\fP
was launched (e.g. \fChttp://localhost:8081/mystore\fP),
it will establish a connection with the store specified in the request,
send a command to read the store's value,
obtain the value,
and respond with it as the document sent with the HTTP response.
.PP
A request for the resource \fC.server?quit\fP, will cause the server
to terminate processing and exit.
.PP
\fIsgsh-httpval\fP is normally executed from within \fIsgsh\fP-generated
scripts, rather than through end-user commands.
This manual page serves mainly to document its operation and
the flags that can be passed to \fIsgsh\fP for modifying its behavior.

.SH OPTIONS
.IP "\fB\-a\fP
Allow any Internet host to obtain a value from the server.
By default the server will only respond to requests arriving from the local
host's loop-back IP address (127.0.0.1).

.IP "\fB\-p\fP \fIMIME-type\fP"
Specify the MIME-type that the server will provide on the \fCContent-type\fP
HTTP header.
By default this value is \fCtext/plain\fP.
Other reasonable types are \fCtext/xml\fP,
\fCtext/CSV\fP, or \fCapplication/octet-stream\fP.

.IP "\fB\-p\fP \fIport\fP"
Specify the TCP port on which the server will listen for incoming HTTP
requests.
If no port is specified, then the server will listen on an arbitrary,
system-assigned, port,
and will print that port's number on its standard output.
That value can be conveniently piped into \fIsgsh-writeval\fP
to be made available to other processes.

.SH "SEE ALSO"
\fIsgsh\fP(1),
\fIsgsh-writeval\fP(1),
\fIsgsh-readval\fP(1)

.SH BUGS
The server is single-threaded and will block if a value is not available
on a specified store.

.SH AUTHOR
Diomidis Spinellis \(em <http://www.spinellis.gr>.
Jef Poskanzer \(em <jef@mail.acme.com> \(em wrote micro_httpd on which
this server is based.
