.TH SGSH-WRAP 1 "15 July 2016"
.\"
.\" (C) Copyright 2016 Diomidis Spinellis.  All rights reserved.
.\"
.\"  Licensed under the Apache License, Version 2.0 (the "License");
.\"  you may not use this file except in compliance with the License.
.\"  You may obtain a copy of the License at
.\"
.\"      http://www.apache.org/licenses/LICENSE-2.0
.\"
.\"  Unless required by applicable law or agreed to in writing, software
.\"  distributed under the License is distributed on an "AS IS" BASIS,
.\"  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
.\"  See the License for the specific language governing permissions and
.\"  limitations under the License.
.\"
.SH NAME
sgsh-wrap \- allow any filter program to participate in an sgsh pipeline
.SH SYNOPSIS
\fBsgsh-wrap\fP
[\fB\-d\fP | \fB-m\fP]
\fIprogram\fP [...]
.SH DESCRIPTION
\fIsgsh-wrap\fP takes as arguments an absolute path or the name
of a program to execute and its arguments.
It will participate in the \fIsgsh\fP negotiation process,
and then execute the specified program connected to the negotiated
input and output pipes.
If the program is not specified through an absolute path,
it will be executed by searching the existing path.

.SH OPTIONS
.IP "\fB\-d\fP
Do not read input; d for deaf.

.IP "\fB\-m\fP
Do not write output; m for mute.

.SH "SEE ALSO"
\fIsgsh\fP(1)

.SH AUTHOR
Diomidis Spinellis \(em <http://www.spinellis.gr>
