.TH SGSH-MONITOR 1 "24 May 2013"
.\"
.\" (C) Copyright 2013 Diomidis Spinellis.  All rights reserved.
.\"
.\"  Licensed under the Apache License, Version 2.0 (the "License");
.\"  you may not use this file except in compliance with the License.
.\"  You may obtain a copy of the License at
.\"
.\"      http://www.apache.org/licenses/LICENSE-2.0
.\"
.\"  Unless required by applicable law or agreed to in writing, software
.\"  distributed under the License is distributed on an "AS IS" BASIS,
.\"  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
.\"  See the License for the specific language governing permissions and
.\"  limitations under the License.
.\"
.SH NAME
sgsh-monitor \- monitor data on a pipe
.SH SYNOPSIS
\fBsgsh-monitor\fP
.SH DESCRIPTION
\fIsgsh-monitor\fP is a filter that reads lines from its standard input
and prepends each one with a timestamp, the number of lines read, and
the number of bytes read.
The values printed are those that were in effect before the line's
first character was read (i.e. the number of bytes and lines starts at 0).
The timestamp is printed as a decimal number of seconds since epoch
(January 1 1970) with microsecond precision.
The command is used internally by \fIsgsh\fP for providing monitoring ports.

.SH "SEE ALSO"
\fIsgsh\fP(1),
\fIsgsh-writeval\fP(1)

.SH AUTHOR
Diomidis Spinellis \(em <http://www.spinellis.gr>
