.TH DGSH-WRAP 1 "15 July 2016"
.\"
.\" (C) Copyright 2016 Diomidis Spinellis.  All rights reserved.
.\"
.\"  Licensed under the Apache License, Version 2.0 (the "License");
.\"  you may not use this file except in compliance with the License.
.\"  You may obtain a copy of the License at
.\"
.\"      http://www.apache.org/licenses/LICENSE-2.0
.\"
.\"  Unless required by applicable law or agreed to in writing, software
.\"  distributed under the License is distributed on an "AS IS" BASIS,
.\"  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
.\"  See the License for the specific language governing permissions and
.\"  limitations under the License.
.\"
.SH NAME
dgsh-wrap \- allow any filter program to participate in an dgsh pipeline
.SH SYNOPSIS
\fBdgsh-wrap\fP
[\fB\-d\fP | \fB-m\fP | \fB\-s\fP]
\fIprogram\fP [...]
.SH DESCRIPTION
\fIdgsh-wrap\fP takes as arguments an absolute path or the name
of a program to execute and its arguments.
It will participate in the \fIdgsh\fP negotiation process,
and then execute the specified program connected to the negotiated
input and output pipes.
If the program is not specified through an absolute path,
it will be executed by searching the existing path.
.PP
Arguments specified as \fI<|\fP will be presented as additional
input channels and will be suitably replaced by named file descriptors
when the command is invoked.
.PP
In the context of a \fIdgsh\fP graph, \fIdgsh(1)\fP uses \fIdgsh-wrap\fP
to allow non-dgsh compatible commands to participate in the negotiation
procedure.

.SH OPTIONS
.IP "\fB\-d\fP
The wrapped program is deaf, it will not read any input.

.IP "\fB\-m\fP
The wrapped program is mute, it will not produce any output.

.IP "\fB\-s\fP
Include standard input to the channel assignments.
This option is used in conjunction with \fI<|\fP and has the effect of
having standard input mapped to the first \fI<|\fP argument and passed to the
wrapped command through it, rather than having the standard input left
connected to the command's standard input.

.SH "SEE ALSO"
\fIdgsh\fP(1)

.SH AUTHOR
Diomidis Spinellis \(em <http://www.spinellis.gr>
