.TH DGSH-WRAP 1 "13 April 2017"
.\"
.\" (C) Copyright 2016-2017 Diomidis Spinellis.  All rights reserved.
.\"
.\"  Licensed under the Apache License, Version 2.0 (the "License");
.\"  you may not use this file except in compliance with the License.
.\"  You may obtain a copy of the License at
.\"
.\"      http://www.apache.org/licenses/LICENSE-2.0
.\"
.\"  Unless required by applicable law or agreed to in writing, software
.\"  distributed under the License is distributed on an "AS IS" BASIS,
.\"  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
.\"  See the License for the specific language governing permissions and
.\"  limitations under the License.
.\"
.SH NAME
dgsh-wrap \- allow any program to participate in an dgsh pipeline
.SH SYNOPSIS
\fBdgsh-wrap\fP
[\fB-S\fP] [\fB-deImO\fP] \fIprogram\fP [\fIprogram-arguments\fP ...]

#!/usr/libexec/dgsh/\fBdgsh-wrap\fP
\fB-s\fP [\fB-deImO\fP] [\fIprogram-arguments\fP ...]

.SH DESCRIPTION
\fIdgsh-wrap\fP takes as arguments an absolute path or the name
of a program to execute and its arguments.
It will participate in the \fIdgsh\fP negotiation process,
and then execute the specified program connected to the negotiated
input and output pipes.
If the program is not specified through an absolute path,
it will be executed by searching the existing path,
excluding from it elements ending in \fIdgsh\fP
(where programs already wrapped with \fIdgsh-wrap\fP may reside).
.PP
Arguments specified as \fI<|\fP are presented as additional
input channels and
arguments specified as \fI>|\fP are presented as additional
output channels.
Both are suitably replaced by named file descriptor paths
when the command is invoked.
.PP
In the context of a \fIdgsh\fP process graph, \fIdgsh(1)\fP automatically
invokes \fIdgsh-wrap\fP to allow non-dgsh compatible commands to participate
in the negotiation procedure.
Furthermore, the \fIdgsh\fP installation process sets up many POSIX programs
wrapped with \fIdgsh-wrap\fP in order to communicate their particular
I/O requirements.

.SH OPTIONS
.IP "\fB\-d\fP
The wrapped program is deaf, it will not read any input.

.IP "\fB\-e\fP
Replace \fI<|\fP and \fI>|\fP strings embedded within arguments,
with names of input file descriptor paths.
By default, only standalone arguments are thus replaced.

.IP "\fB\-I\fP
Do not include the standard input to the command line arguments,
when replacing \fI<|\fP arguments with names of input file descriptor paths.
This will result in the standard input becoming available to the
command as its standard input, rather than as a command line argument.
Without this option, the first path with be \fI/proc/self/fd/0\fP.
When this option is given, the program will require one input channel
more than those specified by the \fI<|\fP arguments.

.IP "\fB\-m\fP
The wrapped program is mute, it will not produce any output.

.IP "\fB\-O\fP
Do not include the standard output to the command line arguments,
when replacing \fI>|\fP arguments with names of output file descriptor paths.
This will result in the standard output becoming available to the
command as its standard output, rather than as a command line argument.
Without this option the first path with be \fI/proc/self/fd/1\fP.
When this option is given, the program will require one output channel
more than those specified by the \fI>|\fP arguments.

.IP "\fB\-S\fP
Process flags as a shebang-invoked (\fI#!\fP) interpreter.
This will change the argument processing in two ways.
First, it will cause the arguments being specified on the shebang line to
be properly parsed as separate arguments by splitting them on whitespace.
(Most operating systems pass any of the line's arguments as a single
string to the process.)
Second, it will remove from the arguments the kernel-supplied path
to the script that invoked \fIdgsh-wrap\fP.
(The script path is not needed,
because the program to wrap is specified as an argument.)
If this flag is specified, it must be the first command-line argument.

.IP "\fB\-s\fP
Process flags as a shebang-invoked (\fI#!\fP) interpreter.
This will change the argument processing in two ways.
First, it will split arguments in the shebang line, in the same
way as the \fI-S\fP flag.
Second, it will convert the kernel-supplied absolute path
to the script that invoked \fIdgsh-wrap\fP, into a command name.
If the name of the script is the same as the name of a command to
be wrapped, this path can be used to derive the name of the program to execute,
thus removing the need to supply the name of the program in the
invocation line.

.SH EXAMPLES
.PP
The following examples are given only to illustrate the command's functionality.
Note that most of the wrappings shown here are either performed automatically
or are not required,
because corresponding commands with built-in \fIdgsh\fP support
are already provided.
.PP
Wrap the \fIecho\fP command, specifying that it accepts no input.
.ft C
.ps -1
.nf
dgsh-wrap -d echo hi
.fi
.ps +1
.ft P
.PP
Wrap the \fIcp\fP command, specifying that it does not perform any I/O.
.ft C
.ps -1
.nf
dgsh-wrap -dm cp src-file dest-file
.fi
.ps +1
.ft P
.PP
Wrap the \fIpaste\fP command, supplying its two arguments.
.ft C
.ps -1
.nf
dgsh-wrap -I /usr/bin/paste "<|" "<|"
.fi
.ps +1
.ft P
.PP
Wrap the \fIpaste\fP command, with an invocation that processes the standard
input and uses an additional input argument.
.ft C
.ps -1
.nf
dgsh-wrap /usr/bin/paste - "<|"
.fi
.ps +1
.ft P
.PP
A wrapped version of the \fIuname\fP command can be created with an
interpreter invocation file containing just the following line.
In contrast to a shell script, no shell is ever launched.
.ft C
.ps -1
.nf
#!/usr/libexec/dgsh/dgsh-wrap -S -d /bin/uname
.fi
.ps +1
.ft P
.PP
Even simpler, a wrapped version of the \fIuname\fP command can be created
if
a) the interpreter invocation file is named \fIuname\fP,
b) it resides in a directory named \fIdgsh\fP (so that it will be excluded
from the subsequently used search path), and
c) it contains the following line.
.ft C
.ps -1
.nf
#!/usr/libexec/dgsh/dgsh-wrap -s  -d
.fi
.ps +1
.ft P

.SH "SEE ALSO"
\fIdgsh\fP(1),
\fIdgsh-negotiate\fP(3)

.SH AUTHOR
Diomidis Spinellis \(em <http://www.spinellis.gr>
